### ISSUE TITLE
Document the default username/passwords

### ISSUE THREAD

**Issue by bvk** [eballetbo/chromebooks#2]
Hi,

Thank you for your work. I finally managed to install pure debian on my Samsung Chromebook Plus. But I couldn't login because I don't know the default username and passwords.  Could you please document them in the README?

Thanks,
Chaitanya

**Comment by eballetbo** [comment]
Right, this needs to be documented somewhere. Meanwhile the default username and password is: debian/debian

**Comment by eballetbo** [comment]
Documented after commit: https://github.com/eballetbo/chromebooks/commit/8ce60d130d7fa4b58fd9185ddda917856a0a70c3

Thanks for the report.
