### ISSUE TITLE
Sorry, this isn't an issue, but

### ISSUE THREAD

**Issue by Outraged-Garchomp** [eballetbo/chromebooks#23]
I'd like to do this on my Lenovo 500e Second Gen, but I'd like to keep ChromeOS and my files, apps, extensions, etc, so I just need to confirm a few things;
You said that getting into developer mode will "reboot and reset the system". Does this erase any files/apps etc already on the device, and how much space does the OS to be installed take up?

Thanks for reading!

**Comment by eballetbo** [comment]
Yes, getting into developer mode will "reboot and reset the system", that means you will loose what is already in the device. So what I have and I do on my chromebooks is switch to developer mode when I receive the device. Once is in developer mode you can boot to ChromeOS (internal disk) and the changes that you do from now are permanent (like it wasn't in developer mode, you can upgrade and install applications). 

Developer mode allows you to boot from an external disk (usb or mmc), so when the system boots you can choose if you want to boot from the internal storage and boot ChromeOS or from the external storage and boot whenever you have in the external storage.

**Comment by Outraged-Garchomp** [comment]
Okay, thanks. Sorry if I'm missing something obvious, but is there a way to boot debian from an external disk without erasing everything already on ChromeOS?

**Comment by eballetbo** [comment]
No, data (files and everything that you installed after the factory installation) will be erased when enabling or disabling Developer Mode. Once in developer mode, as I said you have dual booting,  you're being able to boot from the internal device which has a ChromeOS factory system or boot from an external disk (i.e debian or fedora).

So if you want to enable developer mode I'd recommend to backup all your files and restore again when you switched to developer mode, also install the apps and extensions, etc.

**Comment by Outraged-Garchomp** [comment]
Ok, thanks again!
