### ISSUE TITLE
Would be better to install kernel-headers

### ISSUE THREAD

**Issue by bvk** [eballetbo/chromebooks#3]
After I got Debian installed on Chromebook Plus, I noticed there are no GPU drivers installed. When I tried to install the GPU drivers package `mali-midgard-dkms`, apt-get complained that there were no kernel-headers to compile the driver.

Since we are doing direct `modules_install` (instead of creating deb packages), we should also `headers_install` for complete-ness.

**Comment by eballetbo** [comment]
Patches are welcome :-)

BTW, my main purpose is use panfrost instead.

**Comment by bvk** [comment]
Do you use panfrost with wayland or xorg?  Do youtube videos play smooth?

**Comment by eballetbo** [comment]
Sorry, this project was silently unmaintained for a while and I don't have access to this hardware anymore. Last time I tried panfrost was working fairly well. I'm going to close the issue, please reopen if is still not working and you are still interested. I plan to take again and rework a bit the project in the near future.
