### ISSUE TITLE
Black screen only on Acer Chromebook R13

### ISSUE THREAD

**Issue by andreimpopescu** [eballetbo/chromebooks#5]
Hello,

Tried this with a native build on an arm64 board using the toolchain from Debian unstable (CROSS_COMPILE=/usr/bin/aarch64-linux-gnu-).

It booted to a blank black screen (backlight was on though).

The (ancient) kernel from archlinuxarm.org works mostly ok with a Debian stable root.

Please let me know if there is anything I can try / test / etc. to get the R13 working with a mainline kernel.

Thanks,
Andrei

**Comment by eballetbo** [comment]
I also had problems with the toolchain from Debian unstable but didn't have time to look in detail. Could you make sure your repo is up-to-date and try to use the default toolchain (the one that is downloaded)?

**Comment by andreimpopescu** [comment]
As far as I can tell the default toolchain is for cross building from amd64, I can only do native (arm64) builds as this is the only hardware available for me to use with Debian (or linux in general).

**Comment by eballetbo** [comment]
This project was silently unmaintained for a while and I don't have access to this hardware anymore but last time I tried was working. I'm going to close the issue, please reopen if is still not working and you are still interested. I plan to take again and rework a bit the project in the near future.
