### ISSUE TITLE
sudo: unable to execute ./chromebook-setup.sh: Permission denied, when executing the chromebook-sh script

### ISSUE THREAD

**Issue by jonathan011Hh** [eballetbo/chromebooks#55]
sudo: unable to execute ./chromebook-setup.sh: Permission denied, I'm also getting error: "command not found" and "no such file or directory" pls help.

**Comment by eballetbo** [comment]
The 'permission denied' error in bash typically occurs when you try to execute a file or command without the necessary permissions. So, please check if chromebook-setup.sh has execute permissions, if not you can add with `chmod +x chromebook-setup.sh`

**Comment by eballetbo** [comment]
Were you able to run the script once execution permissions were done?

**Comment by eballetbo** [comment]
Doesn't look like an issue just a permissions problems, so closing it. Feel free to reopent if that's not the case.
